version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_NAME=Plataforma Educativa
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=plataforma_educativa
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=plataforma_educativa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
